# This is a basic workflow to help you get started with Actions

name: Build Linux Libraries

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the regression2 branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake patchelf
      # Runs a set of commands using the runners shell
      - name: Clone OpenCV
        run: |
          cd ~
          git clone https://github.com/opencv/opencv.git -b 4.5.3 --depth=1

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          remove_stale_cache: false

      - name: Build OpenCV
        run: |
            cd ~/opencv
            mkdir build && cd build
            cmake \
              -DCMAKE_BUILD_TYPE=RELEASE \
              -DENABLE_CCACHE=ON \
              -DBUILD_SHARED_LIBS=ON \
              -DWITH_IPP=OFF \
              -DBUILD_IPP_IW=OFF \
              -DWITH_LAPACK=OFF \
              -DWITH_EIGEN=OFF \
              -DBUILD_ZLIB=OFF \
              -DBUILD_OPENEXR=ON \
              -DWITH_JPEG=ON \
              -DBUILD_JPEG=ON \
              -DWITH_PNG=ON \
              -DWITH_PROTOBUF=OFF \
              -DBUILD_PNG=ON \
              -DWITH_TIFF=ON \
              -DBUILD_TIFF=ON \
              -DBUILD_TESTS=OFF \
              -DBUILD_PERF_TESTS=OFF \
              -DBUILD_EXAMPLES=OFF \
              -DWITH_FFMPEG=OFF \
              -DCMAKE_INSTALL_PREFIX=~/opencv4 \
              -DBUILD_opencv_world=ON \
              ..
            make -j$(nproc --all)
            make install

      - name: Patch OpenCV
        run: |
            mkdir ~/build
            cd ~/opencv4/lib
            REAL_OPENCV=$(realpath libopencv_world.so)
            patchelf --set-soname libopencv_world.so ${REAL_OPENCV}
            patchelf --set-rpath '$ORIGIN/../3rdparty/lib:$ORIGIN/lib:$ORIGIN' ${REAL_OPENCV}
            cp ${REAL_OPENCV} ~/build/libopencv_world.so

      - name: Package OpenCV
        run: |
            cd ~
            tar -czvf build/OpenCV.tar.gz opencv4

      - name: Clone FastDeploy
        run: |
            cd ~
            git clone https://github.com/PaddlePaddle/FastDeploy.git -b release/1.0.0 --depth=1

      - name: Build FastDeploy
        run: |
            cd ~/FastDeploy
            mkdir build && cd build
            cmake \
              -DENABLE_ORT_BACKEND=ON \
              -DCMAKE_INSTALL_PREFIX=~/compiled_fastdeploy_sdk \
              -DENABLE_VISION=ON \
              -DOPENCV_DIRECTORY=~/opencv4/lib/cmake/opencv4/ \
              ..
            make -j$(nproc --all)
            make install

      - name: Patch FastDeploy
        run: |
            cd ~/FastDeploy/build
            REAL_FASTDEPLOY=$(realpath libfastdeploy.so)
            patchelf --set-soname libfastdeploy.so ${REAL_FASTDEPLOY}
            ldd libfastdeploy.so
            libs=$(ldd libfastdeploy.so | grep FastDeploy | sed 's/.*=> \(.*\) (.*)/\1/g')
            for lib in $libs
            do
              cp $lib ~/build/;
            done
            patchelf --set-rpath '$ORIGIN/../3rdparty/lib:$ORIGIN/lib:$ORIGIN' ${REAL_FASTDEPLOY}
            cp ${REAL_FASTDEPLOY} ~/build/libfastdeploy.so

      - name: Upload Libs
        uses: actions/upload-artifact@v3
        with:
          name: Libraries
          path: ~/build

